#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Ricky Laney <rlaneyjr@gmail.com>
#
# ### zprofile
# 
# This file is similar to zlogin, but it is sourced before zshrc. It was added
# for [KornShell][1] fans. See the description of zlogin below for what it may
# contain.
# 
# zprofile and zlogin are not meant to be used concurrently but can be done so.
########################################
# ### zlogin
# 
# This file is sourced by login shells after zshrc, and thus, it should contain
# commands that need to execute at login. It is usually used for messages such as
# [fortune][2], [msgs][3], or for the creation of files.
# 
# This is not the file to define aliases, functions, shell options, and key
# bindings. It should not change the shell environment.
########################################
# The configuration files are read in the following order:
# 
#   01. /etc/zshenv
#   02. ~/.zshenv
#   03. /etc/zprofile
#   04. ~/.zprofile
#   05. /etc/zshrc
#   06. ~/.zshrc
#   07. ~/.zpreztorc
#   08. /etc/zlogin
#   09. ~/.zlogin
#   10. ~/.zlogout
#   11. /etc/zlogout
########################################

########################################
#            Load First                #
########################################
# Stuff that needs to be loaded first due to dependencies.
export ZSH_CUSTOM=$HOME/.zsh
#export TERM='xterm-256color'
export TERM='xterm-256color-italic'
#export TERM='screen-256color'

# Browser
if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

# Make vim the default editor.
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

# Language
# Prefer US English and use UTF-8.
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi
if [[ -z "$LC_ALL" ]]; then
  export LC_ALL='en_US.UTF-8'
fi
# Set architecture flags
# if [[ -z "$ARCHFLAGS" ]]; then
#   export ARCHFLAGS='-arch x86_64'
# fi

# Paths
# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path manpath

# Set the list of directories that cd searches.
cdpath=(
    /Users/rlaney
    /Users/rlaney/{bin,lib,scripts,temp,tmp}
    /Users/rlaney/{cheaters,repos,DB}
    /Users/rlaney/{Projects,Workshops,Documents,PycharmProjects}
    /Users/rlaney/"Creative Cloud Files"
    /Users/rlaney/"Dropbox (Personal)"
    $cdpath
)

# Set the list of directories that Zsh searches for programs.
path=(
    $HOME/.poetry/bin
    /usr/local/opt/coreutils/libexec/gnubin
    /usr/local/{bin,sbin}
    /Applications
    $HOME/.go/bin
    $HOME/.jenv/bin
    /Users/rlaney/{bin,lib,scripts}
    /opt/X11/bin
    /opt/cisco/anyconnect/bin
    /opt/vagrant/bin
    /Applications/VMware Fusion.app/Contents/Library
    /Applications/Wireshark.app/Contents/MacOS/extcap
    /Applications/Wireshark.app/Contents/MacOS
    $path
)

# load our own completions (~/.zsh/completion)
fpath=(
    $HOME/.zsh/completion
    /usr/local/share/zsh/functions
    /usr/local/share/zsh/site-functions
    /usr/local/share/zsh-completions
    $fpath
)

    # Removed path:
#    $HOME/.go/bin
#    $HOME/.jenv/bin
#    $HOME/.rvm/bin
#    $HOME/.zsh/functions
#    /usr/local/opt/node@8/bin
#    /usr/local/opt/bzip2/bin
#    /usr/local/opt/icu4c/bin
#    /usr/local/opt/icu4c/sbin
#    /usr/local/opt/openssl/bin
#    /usr/local/opt/tcl-tk/bin
#    /usr/local/opt/sqlite/bin
#    /usr/local/opt/libpq/bin
#    /usr/local/opt/libxml2/bin
#    /usr/local/opt/go/libexec/bin
#    /usr/local/opt/bison/bin
#    /usr/local/opt/qt/bin
#    /usr/local/opt/ncurses/bin
#    /usr/local/opt/sphinx-doc/bin

    # Removed fpath:
#    /usr/local/etc/bash_completion.d
#    /usr/local/etc/profile.d/bash_completion.sh
#    /usr/local/Homebrew/completions/zsh
#    /usr/share/zsh/5.3/functions
#    /usr/share/zsh/site-functions
#    /usr/local/share/cmake/completions
#    /usr/local/share/bash-completion
#    /usr/local/share/bash-completion/bash-completion
#    /usr/local/share/bash-completion/completions

# enable colored output from ls, etc. on FreeBSD-based systems
export CLICOLOR=1

# Less
# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
#export LESS='-F -g -i -M -R -S -w -X -z-4'
export LESS='-g -i -M -R -S -w -z -4'

# Get color support for 'less'
# export LESS="--RAW-CONTROL-CHARS"
# export LESS='--ignore-case --raw-control-chars'
# Load LESS_TERMCAP color variables for less, man, etc., colorful
[[ -f ~/.LESS_TERMCAP ]] && source ~/.LESS_TERMCAP

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

##### COREUTILS ADDED to "PATH" and "MANPATH" #####
# All commands have been installed with the prefix 'g'.
# If you really need to use these commands with their normal names, you
# can add a "gnubin" directory to your PATH from your bashrc like:
#     PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
# Additionally, you can access their man pages with normal names if you add
# the "gnuman" directory to your MANPATH from your bashrc as well:
#     MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

############################################################
# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';
export MANPATH="$MANPATH:/usr/local/man"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

